variables:
  JEKYLL_ENV: production

before_script:
  - bundle install
  - npm install
  - ./node_modules/bower/bin/bower install
  - ./node_modules/gulp/bin/gulp.js

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master