variables:
  JEKYLL_ENV: production

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - bundle install --path=vendor
  - npm install
  - ./node_modules/bower/bin/bower install
  - ./node_modules/gulp/bin/gulp.js
  - echo -n "baseurl:" | tee branch.yml
  - echo " /${CI_COMMIT_REF_SLUG}" >> branch.yml
  - cat branch.yml
  - bundle exec jekyll build -d built --config _config.yml,branch.yml
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
    - vendor/
  artifacts:
    paths:
    - built


test:
  stage: test
  script:
  - echo "Link checker"
  - ls

deploy_staging:
  stage: deploy
  script:
  - echo "Deploy Staging"
  - rsync -av --delete ./built/ /mnt/nfs/site-content/jekyll/${CI_PROJECT_NAMESPACE$}/{CI_COMMIT_REF_SLUG}/