variables:
  JEKYLL_ENV: production

stages:
  - build
  - test
  - deploy

before_script:
  - bundle install --path=vendor
  - npm install
  - ./node_modules/bower/bin/bower install
  - ./node_modules/gulp/bin/gulp.js

build:
  stage: build
  script:
  - bundle exec jekyll build -d built
  artifacts:
    paths:
    - built

test:
  stage: test
  script:
  - echo "Link checker"
  artifacts:
    paths:
    - built

deploy_prod:
  stage: deploy
  script:
  - echo "Deploy Production"
  artifacts:
    paths:
    - built
  only:
  - master 

deploy_staging:
  stage: deploy
  script:
  - echo "Deploy Staging"
  artifacts:
    paths:
    - built
  only:
  - staging